apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Daemon                    Off
        Log_Level                 info
        Parsers_File              parsers.conf
        Parsers_File              custom_parsers.conf
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        Health_Check              On

    [INPUT]
        Name                systemd
        Tag                 host.*
        Read_From_Tail      On
        Strip_Underscores   On

    [INPUT]
        Name                tail
        Tag                 container.*
        Path                /var/log/containers/*_durga-streaming_*.log
        Parser              cri
        DB                  /var/log/flb_kube.db
        DB.locking          true
        Mem_Buf_Limit       50MB
        Skip_Long_Lines     On

    [FILTER]
        Name                kubernetes
        Match               container.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     container.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              On
        Annotations         On

    [OUTPUT]
        Name                cloudwatch_logs
        Match               container.*
        region              eu-west-2
        log_group_name      /aws/eks/durga-streaming-app/application
        log_stream_prefix   from-fluent-bit-
        auto_create_group   false
        workers             1
        retry_limit         2

    [OUTPUT]
        Name                cloudwatch_logs
        Match               host.*
        region              eu-west-2
        log_group_name      /aws/eks/durga-streaming-app/cluster
        log_stream_prefix   host-
        auto_create_group   false
        workers             1
        retry_limit         2

  custom_parsers.conf: |
    [PARSER]
        Name                cri
        Format              regex
        Regex               ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep           On

    [PARSER]
        Name                json
        Format              json
        Time_Key            timestamp
        Time_Format         %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep           On
